#!/usr/bin/env sh
alias ka="killall" \
  p="sudo pacman" \
  SS="sudo systemctl" \
  g="git" \
  e="$EDITOR" \
  v="$EDITOR" \
  sdn="sudo shutdown -h now" \
  ls="ls -hN --color=auto --group-directories-first" \
  grep="rg" \
  diff="diff --color=auto" \
  ccat="highlight --out-format=ansi" \
  ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
  lsp="pacman -Qett --color=always | less" \
  mkdir='mkdir -pv' \

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % $EDITOR % ;}
