#!/usr/bin/env sh
alias ka="killall" \
  p="paru -Sl --color=always | awk '{print \$2\" \"\$3\" \"\$4\" \"\$5}' | fzf --ansi -m --preview 'paru -Si {1}' | awk '{print \$1}' | xargs -r paru --noconfirm --skipreview -Sy" \
  pr="paru -Qett --color=always | fzf --ansi -m --preview 'paru -Si {1}' | awk '{print \$1}' | xargs -r sudo paru --noconfirm -Rncs" \
  pm="sudo pacman" \
  SS="sudo systemctl" \
  g="git" \
  e="$EDITOR" \
  v="$EDITOR" \
  sdn="sudo shutdown -h now" \
  ls="exa -l --color=always --group-directories-first" \
  la="exa -al --color=always --group-directories-first" \
  grep="rg" \
  diff="diff --color=auto" \
  ccat="highlight --out-format=ansi" \
  ref="shortcuts >/dev/null; source ~/.config/shortcutrc" \
  lsp="pacman -Qett --color=always | less" \
  mkdir='mkdir -pv' \
  dot='git --git-dir=$HOME/.config/dotsGit --work-tree=$HOME' \
  cat='bat --color=always' \
  sudo='sudo ' \
  bt='bluetoothctl connect 00:16:94:1A:6B:3A' \

command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" # Use neovim for vim if present.

vf() { fzf | xargs -r -I % $EDITOR % ;}
