#!/usr/bin/env sh

xsetroot -cursor_name left_ptr  # Set default cursor to pointer
setbg &                         # Set the background
pkill sxhkd                     # Ensure only one instance running
sxhkd &                         # Bind keys
xset s 600 600                  # Monitor sleep after 10 mins
xset r rate 175 50              # Speed xrate up [delay] [rate]
dunst &                         # dunst for notifications
clipmenud &                     # Clipmenu for accessing copy history
touchegg &                      # Touchpad gestures

# Adjust mouse sensitivity
if [[ $HOSTNAME = "xps" ]]; then
    Touchpad=`xinput list \
    | rg -i "Touchpad" \
    | awk -F= '{ print $2}' \
    | awk '{print $1}' \
    | awk 'BEGIN{ RS = "" ; FS = "\n" }{print $1}'`
    xinput set-prop $Touchpad "Coordinate Transformation Matrix" 10 0 0 0 10 0 0 0 1
    xinput set-prop $Touchpad "libinput Tapping Enabled" "1"
    xinput set-prop $Touchpad "libinput Natural Scrolling Enabled" "1"
    xinput set-prop $Touchpad "libinput Accel Profile Enabled" 0, 1
elif [[ $HOSTNAME = "grill" ]]; then
    DeathAdder=`xinput list \
    | rg -i "Razer Razer DeathAdder 2013" \
    | awk -F= '{ print $2}' \
    | awk '{print $1}' \
    | awk 'BEGIN{ RS = "" ; FS = "\n" }{print $1}'`
    xinput set-prop $DeathAdder "Coordinate Transformation Matrix" .6 0 0 0 .6 0 0 0 1
fi
